Add mirror option
Signed-off-by: Tyler Nijmeh <tylernij@gmail.com>

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -4,6 +4,31 @@
 # Destination repository or organization
 DEST_REPO="https://github.com/Magisk-Modules-Alt-Repo"
 
+usage() {
+	echo -n "Usage: `basename $0` [OPTIONS] <REPO-USER> <REPO-NAME>
+Options:
+  -m			Mirror instead of clone (add cron workflow)
+  -h			Show usage
+"
+}
+
+while getopts ":dm" opt; do
+	case $opt in
+		m)
+			MIRROR=1
+			;;
+		h)
+			usage
+			exit 0
+			;;
+		*)
+			usage
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND-1))
+
 # Origin repo author
 REPO_USER="$1"
 
@@ -54,6 +79,9 @@ DESCRIPTION=`curl -s							\
 # Use no description rather than 'null'
 [[ "$DESCRIPTION" == "null" ]] && DESCRIPTION=""
 
+# Change description if we are a mirror repo
+[[ "$MIRROR" -eq 1 ]] && DESCRIPTION="[Mirror] $DESCRIPTION"
+
 # Create base repo on destination organization with [Mirror] descriptor
 curl -s									\
 	-u $GIT_USER:$GIT_TOKEN						\
@@ -63,7 +91,7 @@ curl -s									\
 	-d '
 {
 	"name":"'"$REPO_NAME"'",
-	"description":"[Mirror] '"$DESCRIPTION"'"
+	"description":"'"$DESCRIPTION"'"
 }'
 
 sleep 5
@@ -81,20 +109,24 @@ git -C base-repo push --mirror "$DEST_REPO_AUTH/$REPO_NAME"
 # Cleanup
 rm -rf base-repo
 
-# Reclone as an actual repo
-git clone "$DEST_REPO/$REPO_NAME" base-repo-v2
+# Add workflow if we are mirroring
+if [[ "$MIRROR" -eq 1 ]]
+then
+	# Reclone as an actual repo
+	git clone "$DEST_REPO/$REPO_NAME" base-repo-v2
 
-# Copy our workflow to auto-update the mirror
-cp -r extra/. base-repo-v2/
+	# Copy our workflow to auto-update the mirror
+	cp -r extra/. base-repo-v2/
 
-# Commit
-git -C base-repo-v2 add .
-git -C base-repo-v2 commit -sam "AUTOMATED: Add automatic mirror fetching action"
+	# Commit
+	git -C base-repo-v2 add .
+	git -C base-repo-v2 commit -sam "AUTOMATED: Add automatic mirror fetching action"
 
-# Push
-git -C base-repo-v2 push "$DEST_REPO_AUTH/$REPO_NAME"
+	# Push
+	git -C base-repo-v2 push "$DEST_REPO_AUTH/$REPO_NAME"
 
-# Cleanup
-rm -rf base-repo-v2
+	# Cleanup
+	rm -rf base-repo-v2
+fi
 
-dbg "Done. Mirrored to $DEST_REPO/$REPO_NAME."
+dbg "Done. Migrated to $DEST_REPO/$REPO_NAME."
